# Generated by Django 4.2.5 on 2023-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YearlyScholarshipData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("semester", models.CharField(max_length=50)),
                ("total_applications", models.PositiveIntegerField()),
                ("total_accepted", models.PositiveIntegerField()),
                ("total_rejected", models.PositiveIntegerField()),
                ("total_new", models.PositiveIntegerField()),
                ("total_renewing", models.PositiveIntegerField()),
                ("total_graduates", models.PositiveIntegerField()),
                ("total_basic_plus", models.PositiveIntegerField()),
                ("total_basic_plus_new", models.PositiveIntegerField()),
                ("total_basic_plus_renewing", models.PositiveIntegerField()),
                ("total_basic_scholarship", models.PositiveIntegerField()),
                ("total_basic_scholarship_new", models.PositiveIntegerField()),
                ("total_basic_scholarship_renewing", models.PositiveIntegerField()),
                ("total_suc_luc", models.PositiveIntegerField()),
                ("total_suc_luc_new", models.PositiveIntegerField()),
                ("total_suc_luc_renewing", models.PositiveIntegerField()),
                ("total_honors", models.PositiveIntegerField()),
                ("total_honors_new", models.PositiveIntegerField()),
                ("total_honors_renewing", models.PositiveIntegerField()),
                ("total_premier", models.PositiveIntegerField()),
                ("total_premier_new", models.PositiveIntegerField()),
                ("total_premier_renewing", models.PositiveIntegerField()),
                ("total_priority", models.PositiveIntegerField()),
                ("total_priority_new", models.PositiveIntegerField()),
                ("total_priority_renewing", models.PositiveIntegerField()),
            ],
        ),
    ]
