# Generated by Django 4.2.5 on 2023-12-05 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("head", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yearlyscholarshipdata",
            old_name="total_suc_luc",
            new_name="total_suc_lcu",
        ),
        migrations.RenameField(
            model_name="yearlyscholarshipdata",
            old_name="total_suc_luc_new",
            new_name="total_suc_lcu_new",
        ),
        migrations.RenameField(
            model_name="yearlyscholarshipdata",
            old_name="total_suc_luc_renewing",
            new_name="total_suc_lcu_renewing",
        ),
    ]
