# Generated by Django 4.2.5 on 2023-10-07 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_officer_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officer",
            name="birthdate",
        ),
    ]
