# Generated by Django 4.2.5 on 2023-10-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_officer_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officer",
            name="district",
            field=models.IntegerField(null=True),
        ),
    ]
