# Generated by Django 4.2.5 on 2023-10-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0004_alter_officer_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("uid", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "applicant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demographics.applicant",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scholars",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "scholarship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demographics.scholarshiptype",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scholars_user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
        migrations.AddField(
            model_name="officer",
            name="gender",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="demographics.gender",
            ),
        ),
        migrations.AlterField(
            model_name="officer",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="officers",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="officer",
            name="middlename",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="officer",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="officers_user_permissions",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
