# Generated by Django 4.2.5 on 2023-10-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0002_alter_applicant_gender"),
        ("accounts", "0005_scholar_delete_gender_officer_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officer",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demographics.gender",
            ),
        ),
    ]
