# Generated by Django 4.2.5 on 2023-10-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_officer_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholar",
            old_name="applicant_id",
            new_name="applicant",
        ),
        migrations.AddField(
            model_name="scholar",
            name="role",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.role",
            ),
        ),
        migrations.AlterField(
            model_name="officer",
            name="district",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
