# Generated by Django 4.2.5 on 2023-10-12 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0010_rename_applicant_id_scholar_applicant_scholar_role_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="officer",
            old_name="uid",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="scholar",
            old_name="uid",
            new_name="username",
        ),
    ]
