# Generated by Django 4.2.5 on 2023-10-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0013_delete_applicant'),
        ('accounts', '0014_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='scholarship_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='demographics.scholarshiptype'),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='years_of_residency',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
