# Generated by Django 4.2.5 on 2023-10-14 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_headprofile_user_alter_officerprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='officerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scholarprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
