# Generated by Django 4.2.5 on 2023-10-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.PositiveSmallIntegerField(choices=[('ONE', '1'), ('TWO', '2')], null=True),
        ),
    ]
