# Generated by Django 4.2.5 on 2023-10-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(choices=[('ONE', '1'), ('TWO', '2')], max_length=3, null=True),
        ),
    ]
