# Generated by Django 4.2.5 on 2023-10-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='barangay',
            field=models.CharField(choices=[('BAGUMBAYAN', 'Bagumbayan'), ('BAMBANG', 'Bambang'), ('CALZADA', 'Calzada'), ('HAGONOY', 'Hagonoy'), ('IBAYO TIPAS', 'Ibayo Tipas'), ('LIGID TIPAS', 'Ligid Tipas'), ('LOWER BICUTAN', 'Lower Bicutan'), ('NEW LOWER BICUTAN', 'New Lower Bicutan'), ('NAPINDAN', 'Napindan'), ('PALINGON', 'Palingon'), ('SAN MIGUEL', 'San Miguel'), ('SANTA ANA', 'Santa Ana'), ('TUKTUKAN', 'Tuktukan'), ('USUSAN', 'Ususan'), ('WAWA', 'Wawa'), ('BAGONG TANYAG', 'Bagong Tanyag'), ('CENTRAL BICUTAN', 'Central Bicutan'), ('CENTRAL SIGNAL VILLAGE', 'Central Signal Village'), ('FORT BONIFACIO', 'Fort Bonifacio'), ('KATUPARAN', 'Katuparan'), ('MAHARLIKA VILLAGE', 'Maharlika Village'), ('NORTH DAANG_HARI', 'North Daang Hari'), ('NORTH SIGNAL VILLAGE', 'North Signal Village'), ('PINAGSAMA', 'Pinagsama'), ('SOUTH DAANG HARI', 'South Daang Hari'), ('SOUTH SIGNAL VILLAGE', 'South Signal Village'), ('UPPER BICUTAN', 'Upper Bicutan'), ('WESTERN BICUTAN', 'Western Bicutan')], max_length=50, null=True),
        ),
    ]
