# Generated by Django 4.2.5 on 2023-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_alter_userprofile_barangay"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarprofile",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scholarprofile",
            name="is_graduated",
            field=models.BooleanField(default=False),
        ),
    ]
