# Generated by Django 4.2.5 on 2023-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_scholarprofile_is_archived_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="contactnumber",
            field=models.CharField(max_length=11),
        ),
    ]
