# Generated by Django 4.2.5 on 2023-10-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_userprofile_contactnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="district",
            field=models.CharField(
                choices=[("ONE", "1"), ("TWO", "2")],
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
