# Generated by Django 4.2.5 on 2023-11-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0013_delete_applicant"),
        ("accounts", "0024_alter_userprofile_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="demographics.gender",
            ),
        ),
    ]
