# Generated by Django 4.2.5 on 2023-11-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0013_delete_applicant"),
        ("accounts", "0026_remove_scholarprofile_facebook_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarprofile",
            name="is_graduated",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="contactnumber",
        ),
        migrations.AddField(
            model_name="scholarprofile",
            name="is_graudating",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scholarprofile",
            name="scholarship_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demographics.scholarshiptype",
            ),
        ),
        migrations.AlterField(
            model_name="scholarprofile",
            name="years_of_residency",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
