# Generated by Django 4.2.5 on 2023-11-17 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_remove_scholarprofile_is_graduated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarprofile",
            old_name="is_graudating",
            new_name="is_graduating",
        ),
    ]
