# Generated by Django 4.2.5 on 2023-11-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_rename_is_graudating_scholarprofile_is_graduating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarprofile",
            name="scholarship_type",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
