# Generated by Django 4.2.5 on 2024-01-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_alter_scholarprofile_scholarship_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarprofile",
            name="years_of_residency",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="middlename",
            field=models.CharField(max_length=100),
        ),
    ]
