# Generated by Django 4.2.5 on 2024-01-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_alter_scholarprofile_years_of_residency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarprofile",
            name="years_of_residency",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="middlename",
            field=models.CharField(max_length=30),
        ),
    ]
