# Generated by Django 4.2.5 on 2023-10-18 03:31

import application.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0021_alter_userprofile_barangay"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("HONORS", "Honors"),
                            ("PREMIER", "Premier"),
                            ("PRIORITY", "Priority"),
                            ("BASIC PLUS", "Basic Plus"),
                            ("BASIC", "Basic"),
                            ("SUC_LCU", "SUC/LCU"),
                            ("REVIEW", "Review"),
                            ("LEAD", "Lead"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                (
                    "academic_year",
                    application.models.AcademicYearField(
                        default="2023-2024", editable=False, max_length=9
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("FIRST SEMESTER", "First Semester"),
                            ("SECOND SEMESTER", "Second Semester"),
                        ],
                        default="FIRST SEMESTER",
                        max_length=20,
                    ),
                ),
                ("gwa", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_applying_for_merit", models.BooleanField(default=False)),
                ("is_eligible", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_graduated", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.officer",
                    ),
                ),
            ],
        ),
    ]
