# Generated by Django 4.2.5 on 2023-10-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0013_delete_applicant"),
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EligibilityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartneredUniversities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="applications",
            name="gwa",
        ),
        migrations.AddField(
            model_name="applications",
            name="applicant_status",
            field=models.CharField(
                choices=[
                    ("NEW APPLICANT", "NEW APPLICANT"),
                    ("RENEWING APPLICANT", "RENEWING APPLICANT"),
                ],
                default="NEW APPLICANT",
                max_length=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="barangay",
            field=models.CharField(
                choices=[
                    ("BAGUMBAYAN", "Bagumbayan"),
                    ("BAMBANG", "Bambang"),
                    ("CALZADA", "Calzada"),
                    ("HAGONOY", "Hagonoy"),
                    ("IBAYO TIPAS", "Ibayo Tipas"),
                    ("LIGID TIPAS", "Ligid Tipas"),
                    ("LOWER BICUTAN", "Lower Bicutan"),
                    ("NEW LOWER BICUTAN", "New Lower Bicutan"),
                    ("NAPINDAN", "Napindan"),
                    ("PALINGON", "Palingon"),
                    ("SAN MIGUEL", "San Miguel"),
                    ("SANTA ANA", "Santa Ana"),
                    ("TUKTUKAN", "Tuktukan"),
                    ("USUSAN", "Ususan"),
                    ("WAWA", "Wawa"),
                    ("BAGONG TANYAG", "Bagong Tanyag"),
                    ("CENTRAL BICUTAN", "Central Bicutan"),
                    ("CENTRAL SIGNAL VILLAGE", "Central Signal Village"),
                    ("FORT BONIFACIO", "Fort Bonifacio"),
                    ("KATUPARAN", "Katuparan"),
                    ("MAHARLIKA VILLAGE", "Maharlika Village"),
                    ("NORTH DAANG_HARI", "North Daang Hari"),
                    ("NORTH SIGNAL VILLAGE", "North Signal Village"),
                    ("PINAGSAMA", "Pinagsama"),
                    ("SOUTH DAANG HARI", "South Daang Hari"),
                    ("SOUTH SIGNAL VILLAGE", "South Signal Village"),
                    ("UPPER BICUTAN", "Upper Bicutan"),
                    ("WESTERN BICUTAN", "Western Bicutan"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="course_duration",
            field=models.CharField(
                choices=[
                    ("THREE YEARS", "THREE (3) YEARS"),
                    ("FOUR YEARS", "FOUR (4) YEARS"),
                    ("FIVE YEARS", "FIVE (5) YEARS"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="district",
            field=models.CharField(
                choices=[("ONE", "1"), ("TWO", "2")], max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="elementary_school",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="elementary_school_address",
            field=models.TextField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="elementary_school_type",
            field=models.CharField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="elementary_start_end",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="email_address",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="fathers_complete_address",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="fathers_complete_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="fathers_contact_number",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="fathers_educational_attainment",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="fathers_occupation",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="fathers_place_of_work",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="firstname",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demographics.gender",
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardians_voter_certificate",
            field=models.FileField(null=True, upload_to="guardian/voters_certificate"),
        ),
        migrations.AddField(
            model_name="applications",
            name="house_address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="informative_copy_of_grades",
            field=models.FileField(null=True, upload_to="applicant/icg"),
        ),
        migrations.AddField(
            model_name="applications",
            name="is_graduating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applications",
            name="is_ladderized",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="jhs_school",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="jhs_school_address",
            field=models.TextField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="jhs_school_type",
            field=models.CharField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="jhs_start_end",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="lastname",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="middlename",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="mothers_complete_address",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="mothers_complete_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="mothers_contact_number",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="mothers_educational_attainment",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="mothers_occupation",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="mothers_place_of_work",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="national_id",
            field=models.ImageField(null=True, upload_to="applicant/ids"),
        ),
        migrations.AddField(
            model_name="applications",
            name="number_of_semesters_before_graduating",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="personalized_facebook_link",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="registration_form",
            field=models.FileField(null=True, upload_to="applicant/registration_form"),
        ),
        migrations.AddField(
            model_name="applications",
            name="religion",
            field=models.CharField(
                choices=[
                    ("ROMAN CATHOLIC", "ROMAN CATHOLIC"),
                    ("PROTESTANT", "PROTESTANT"),
                    ("BAPTIST", "BAPTIST"),
                    ("IGLESIA NI CRISTO", "IGLESIA NI CRISTO"),
                    ("ISLAM", "ISLAM"),
                    ("EVANGELICAL CHRISTIAN", "EVANGELICAL CHRISTIAN"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="shiftee",
            field=models.CharField(
                help_text="Title of your previous course (if shiftee).",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="shs_school",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="shs_school_address",
            field=models.TextField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="shs_school_type",
            field=models.CharField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="shs_start_end",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="student_status",
            field=models.CharField(
                choices=[
                    ("REGULAR", "REGULAR"),
                    ("IRREGULAR", "IRREGULAR"),
                    ("OCTOBERIAN", "OCTOBERIAN"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="total_units_enrolled",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="transferee",
            field=models.CharField(
                help_text="Name of your previous school/university.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="year_level",
            field=models.CharField(
                choices=[
                    ("FIRST YEAR", "FIRST YEAR"),
                    ("SECOND YEAR", "SECOND YEAR"),
                    ("THIRD YEAR", "THIRD YEAR"),
                    ("FOURTH YEAR", "FOURTH YEAR"),
                    ("FIFTH YEAR", "FIFTH YEAR"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="years_of_residency",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="scholarship_type",
            field=models.CharField(
                choices=[
                    ("BASIC PLUS SUC", "BASIC PLUS SUC"),
                    ("SUC_LCU", "SUC/LCU"),
                    ("BASIC SCHOLARSHIP", "BASIC SCHOLARSHIP"),
                    ("HONORS", "HONORS (FULL)"),
                    ("PRIORITY", "PRIORITY"),
                    ("PREMIER", "PREMIER"),
                ],
                default="BASIC SCHOLARSHIP",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="semester",
            field=models.CharField(
                choices=[
                    ("FIRST SEMESTER", "FIRST SEMESTER"),
                    ("SECOND SEMESTER", "SECOND SEMESTER"),
                ],
                default="FIRST SEMESTER",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="course_taking",
            field=models.ForeignKey(
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.courses",
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="university_attending",
            field=models.ForeignKey(
                max_length=40,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.partnereduniversities",
            ),
        ),
    ]
