# Generated by Django 4.2.5 on 2023-10-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_alter_applications_guardians_voter_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="voter_certificate",
            field=models.FileField(null=True, upload_to="applicant/voters_certificate"),
        ),
    ]
