# Generated by Django 4.2.5 on 2023-10-27 08:04

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0006_applications_voter_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilityconfig",
            name="academic_year",
            field=application.models.AcademicYearField(
                default="2023-2024", editable=False, max_length=9
            ),
        ),
        migrations.AddField(
            model_name="eligibilityconfig",
            name="minimum_residency",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="eligibilityconfig",
            name="semester",
            field=models.CharField(
                choices=[
                    ("FIRST SEMESTER", "FIRST SEMESTER"),
                    ("SECOND SEMESTER", "SECOND SEMESTER"),
                ],
                default="FIRST SEMESTER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="eligibilityconfig",
            name="voters_issuance_year",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
