# Generated by Django 4.2.5 on 2023-11-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0008_rename_voters_issuance_year_eligibilityconfig_voters_validity_year_start_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="registration_form",
            field=models.FileField(
                help_text="Insert your Registration Form for the current semeset.",
                null=True,
                upload_to="applicant/registration_form",
            ),
        ),
    ]
