# Generated by Django 4.2.5 on 2023-11-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0009_alter_applications_registration_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="guardians_voter_certificate",
            field=models.FileField(
                help_text="Insert your guardian's voter certificate (for verification and validation purposes).",
                null=True,
                upload_to="guardian/voters_certificate",
            ),
        ),
    ]
