# Generated by Django 4.2.5 on 2023-11-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0010_alter_applications_guardians_voter_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applications",
            name="fathers_complete_address",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="fathers_complete_name",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="fathers_contact_number",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="fathers_educational_attainment",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="fathers_occupation",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="fathers_place_of_work",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="mothers_complete_address",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="mothers_complete_name",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="mothers_contact_number",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="mothers_educational_attainment",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="mothers_occupation",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="mothers_place_of_work",
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_complete_address",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_complete_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_contact_number",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_educational_attainment",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_occupation",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_place_of_work",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
