# Generated by Django 4.2.5 on 2023-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0011_remove_applications_fathers_complete_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="guardian_complete_address",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardian_place_of_work",
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="house_address",
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="registration_form",
            field=models.FileField(
                help_text="Insert your Registration/Enrollment Form for the current semester.",
                null=True,
                upload_to="applicant/registration_form",
            ),
        ),
    ]
