# Generated by Django 4.2.5 on 2023-11-09 08:14

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0013_remove_applications_academic_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default="2023-2024", editable=False, max_length=9
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="informative_copy_of_grades",
            field=models.FileField(null=True, upload_to="applicant/icg"),
        ),
        migrations.AddField(
            model_name="applications",
            name="is_applying_for_merit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applications",
            name="semester",
            field=models.CharField(
                choices=[
                    ("FIRST SEMESTER", "FIRST SEMESTER"),
                    ("SECOND SEMESTER", "SECOND SEMESTER"),
                ],
                default="FIRST SEMESTER",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="voter_certificate",
            field=models.FileField(null=True, upload_to="applicant/voters_certificate"),
        ),
        migrations.AddField(
            model_name="applications",
            name="voters_issued_at",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="years_of_residency",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="firstname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="lastname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="middlename",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
