# Generated by Django 4.2.5 on 2023-11-10 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0014_applications_applying_for_academic_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applications",
            name="applying_for_academic_year",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="informative_copy_of_grades",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="is_applying_for_merit",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="voter_certificate",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="voters_issued_at",
        ),
        migrations.RemoveField(
            model_name="applications",
            name="years_of_residency",
        ),
    ]
