# Generated by Django 4.2.5 on 2023-11-11 02:59

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0020_remove_eligibilityconfig_academic_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="elementary_school",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="elementary_school_address",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="elementary_school_type",
            field=models.CharField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="elementary_start_end",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="jhs_school",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="jhs_school_address",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="jhs_school_type",
            field=models.CharField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="jhs_start_end",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="shs_school",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="shs_school_address",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="shs_school_type",
            field=models.CharField(
                choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="shs_start_end",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
    ]
