# Generated by Django 4.2.5 on 2023-11-11 05:30

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0021_applications_elementary_school_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="guardian_complete_address",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_complete_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_contact_number",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_educational_attainment",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_occupation",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardian_place_of_work",
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardians_voter_certificate",
            field=models.FileField(
                help_text="Insert your SCANNED COPY (IMG) guardian's voter certificate (for verification and validation purposes).",
                null=True,
                upload_to="guardian/voters_certificate",
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardians_voters_issuance_date",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardians_voters_issued_at",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="guardians_years_of_residency",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
    ]
