# Generated by Django 4.2.5 on 2023-11-11 05:52

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0022_applications_guardian_complete_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="number_of_semesters_before_graduating",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="shiftee",
            field=models.CharField(
                default="N/A",
                help_text="Title of your previous course (if shiftee).",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="student_status",
            field=models.CharField(
                choices=[
                    ("REGULAR", "REGULAR"),
                    ("IRREGULAR", "IRREGULAR"),
                    ("OCTOBERIAN", "OCTOBERIAN"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="transferee",
            field=models.CharField(
                default="N/A",
                help_text="Name of your previous school/university.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
    ]
