# Generated by Django 4.2.5 on 2023-11-11 07:18

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0023_applications_number_of_semesters_before_graduating_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardians_years_of_residency",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
    ]
