# Generated by Django 4.2.5 on 2023-11-13 04:49

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0024_alter_applications_applying_for_academic_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="eligibilityconfig",
            name="guardians_minimum_residency",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="firstname",
            field=models.CharField(
                blank=True,
                default="Unable to extract from image.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardians_voters_issuance_date",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardians_voters_issued_at",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="lastname",
            field=models.CharField(
                blank=True,
                default="Unable to extract from image.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="middlename",
            field=models.CharField(
                blank=True,
                default="Unable to extract from image.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.applicationstatus",
            ),
        ),
    ]
