# Generated by Django 4.2.5 on 2023-11-18 13:32

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0014_delete_scholarshiptype"),
        ("application", "0036_alter_applications_applying_for_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.CreateModel(
            name="TempApplications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_reference_id",
                    models.CharField(max_length=20, null=True),
                ),
                (
                    "national_id",
                    models.ImageField(null=True, upload_to="applicant/ids"),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True,
                        default="Unable to extract from image.",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True,
                        default="Unable to extract from image.",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "middlename",
                    models.CharField(
                        blank=True,
                        default="Unable to extract from image.",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("birthdate", models.DateField(null=True)),
                ("house_address", models.TextField(max_length=50, null=True)),
                (
                    "barangay",
                    models.CharField(
                        choices=[
                            ("BAGUMBAYAN", "Bagumbayan"),
                            ("BAMBANG", "Bambang"),
                            ("CALZADA", "Calzada"),
                            ("HAGONOY", "Hagonoy"),
                            ("IBAYO TIPAS", "Ibayo Tipas"),
                            ("LIGID TIPAS", "Ligid Tipas"),
                            ("LOWER BICUTAN", "Lower Bicutan"),
                            ("NEW LOWER BICUTAN", "New Lower Bicutan"),
                            ("NAPINDAN", "Napindan"),
                            ("PALINGON", "Palingon"),
                            ("SAN MIGUEL", "San Miguel"),
                            ("SANTA ANA", "Santa Ana"),
                            ("TUKTUKAN", "Tuktukan"),
                            ("USUSAN", "Ususan"),
                            ("WAWA", "Wawa"),
                            ("BAGONG TANYAG", "Bagong Tanyag"),
                            ("CENTRAL BICUTAN", "Central Bicutan"),
                            ("CENTRAL SIGNAL VILLAGE", "Central Signal Village"),
                            ("FORT BONIFACIO", "Fort Bonifacio"),
                            ("KATUPARAN", "Katuparan"),
                            ("MAHARLIKA VILLAGE", "Maharlika Village"),
                            ("NORTH DAANG_HARI", "North Daang Hari"),
                            ("NORTH SIGNAL VILLAGE", "North Signal Village"),
                            ("PINAGSAMA", "Pinagsama"),
                            ("SOUTH DAANG HARI", "South Daang Hari"),
                            ("SOUTH SIGNAL VILLAGE", "South Signal Village"),
                            ("UPPER BICUTAN", "Upper Bicutan"),
                            ("WESTERN BICUTAN", "Western Bicutan"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[("ONE", "1"), ("TWO", "2")], max_length=3, null=True
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, null=True, unique=True),
                ),
                (
                    "personalized_facebook_link",
                    models.CharField(max_length=30, null=True),
                ),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("ROMAN CATHOLIC", "ROMAN CATHOLIC"),
                            ("PROTESTANT", "PROTESTANT"),
                            ("BAPTIST", "BAPTIST"),
                            ("IGLESIA NI CRISTO", "IGLESIA NI CRISTO"),
                            ("ISLAM", "ISLAM"),
                            ("EVANGELICAL CHRISTIAN", "EVANGELICAL CHRISTIAN"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "applicant_status",
                    models.CharField(
                        choices=[
                            ("NEW APPLICANT", "NEW APPLICANT"),
                            ("RENEWING APPLICANT", "RENEWING APPLICANT"),
                        ],
                        default="NEW APPLICANT",
                        max_length=18,
                        null=True,
                    ),
                ),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("BASIC PLUS SUC", "BASIC PLUS SUC"),
                            ("SUC_LCU", "SUC/LCU"),
                            ("BASIC SCHOLARSHIP", "BASIC SCHOLARSHIP"),
                            ("HONORS", "HONORS (FULL)"),
                            ("PRIORITY", "PRIORITY"),
                            ("PREMIER", "PREMIER"),
                        ],
                        default="BASIC SCHOLARSHIP",
                        help_text="Kindly refer to the guidelines. Fraudulent inputs will deem your application as void.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "applying_for_academic_year",
                    application.models.AcademicYearField(
                        default=application.models.AcademicYearField.calculate_academic_year,
                        editable=False,
                        max_length=9,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("FIRST SEMESTER", "FIRST SEMESTER"),
                            ("SECOND SEMESTER", "SECOND SEMESTER"),
                        ],
                        default="FIRST SEMESTER",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "informative_copy_of_grades",
                    models.FileField(null=True, upload_to="applicant/icg"),
                ),
                (
                    "is_applying_for_merit",
                    models.BooleanField(
                        default=False,
                        help_text="SWA at least 1.75 equivalent to 88.75%).",
                    ),
                ),
                (
                    "voter_certificate",
                    models.FileField(
                        null=True, upload_to="applicant/voters_certificate"
                    ),
                ),
                ("years_of_residency", models.CharField(max_length=30, null=True)),
                (
                    "voters_issued_at",
                    models.CharField(blank=True, max_length=70, null=True),
                ),
                (
                    "voters_issuance_date",
                    models.CharField(blank=True, max_length=70, null=True),
                ),
                (
                    "registration_form",
                    models.FileField(
                        help_text="Insert your Registration/Enrollment Form for the current semester.",
                        null=True,
                        upload_to="applicant/registration_form",
                    ),
                ),
                ("total_units_enrolled", models.PositiveSmallIntegerField(null=True)),
                ("is_ladderized", models.BooleanField(null=True)),
                (
                    "year_level",
                    models.CharField(
                        choices=[
                            ("FIRST YEAR", "FIRST YEAR"),
                            ("SECOND YEAR", "SECOND YEAR"),
                            ("THIRD YEAR", "THIRD YEAR"),
                            ("FOURTH YEAR", "FOURTH YEAR"),
                            ("FIFTH YEAR", "FIFTH YEAR"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("is_graduating", models.BooleanField(default=False)),
                (
                    "course_duration",
                    models.CharField(
                        choices=[
                            ("THREE YEARS", "THREE (3) YEARS"),
                            ("FOUR YEARS", "FOUR (4) YEARS"),
                            ("FIVE YEARS", "FIVE (5) YEARS"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("elementary_school", models.CharField(max_length=50, null=True)),
                (
                    "elementary_school_type",
                    models.CharField(
                        choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "elementary_school_address",
                    models.TextField(max_length=100, null=True),
                ),
                ("elementary_start_end", models.CharField(max_length=9, null=True)),
                ("jhs_school", models.CharField(max_length=50, null=True)),
                (
                    "jhs_school_type",
                    models.CharField(
                        choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("jhs_school_address", models.TextField(max_length=100, null=True)),
                ("jhs_start_end", models.CharField(max_length=9, null=True)),
                ("shs_school", models.CharField(max_length=50, null=True)),
                (
                    "shs_school_type",
                    models.CharField(
                        choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("shs_school_address", models.TextField(max_length=100, null=True)),
                ("shs_start_end", models.CharField(max_length=9, null=True)),
                ("guardian_complete_name", models.CharField(max_length=50, null=True)),
                (
                    "guardian_complete_address",
                    models.TextField(max_length=100, null=True),
                ),
                ("guardian_contact_number", models.CharField(max_length=11, null=True)),
                ("guardian_occupation", models.CharField(max_length=30, null=True)),
                ("guardian_place_of_work", models.TextField(max_length=30, null=True)),
                (
                    "guardian_educational_attainment",
                    models.CharField(max_length=30, null=True),
                ),
                (
                    "guardians_voter_certificate",
                    models.FileField(
                        help_text="Insert your SCANNED COPY (IMG) guardian's voter certificate (for verification and validation purposes).",
                        null=True,
                        upload_to="guardian/voters_certificate",
                    ),
                ),
                (
                    "guardians_years_of_residency",
                    models.CharField(max_length=30, null=True),
                ),
                (
                    "guardians_voters_issued_at",
                    models.CharField(max_length=70, null=True),
                ),
                (
                    "guardians_voters_issuance_date",
                    models.CharField(max_length=70, null=True),
                ),
                (
                    "number_of_semesters_before_graduating",
                    models.PositiveSmallIntegerField(null=True),
                ),
                (
                    "transferee",
                    models.CharField(
                        default="N/A",
                        help_text="Name of your previous school/university.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "shiftee",
                    models.CharField(
                        default="N/A",
                        help_text="Title of your previous course (if shiftee).",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "student_status",
                    models.CharField(
                        choices=[
                            ("REGULAR", "REGULAR"),
                            ("IRREGULAR", "IRREGULAR"),
                            ("OCTOBERIAN", "OCTOBERIAN"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "course_taking",
                    models.ForeignKey(
                        max_length=50,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.courses",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demographics.gender",
                    ),
                ),
                (
                    "university_attending",
                    models.ForeignKey(
                        max_length=40,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.partnereduniversities",
                    ),
                ),
            ],
        ),
    ]
