# Generated by Django 4.2.5 on 2023-11-19 10:35

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0039_alter_applications_applying_for_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardians_voter_certificate",
            field=models.FileField(
                help_text="Insert your SCANNED COPY (IMG) guardian's voter certificate (for verification and validation purposes).",
                null=True,
                upload_to="final/guardian/voters_certificate",
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="informative_copy_of_grades",
            field=models.FileField(null=True, upload_to="final/applicant/icg"),
        ),
        migrations.AlterField(
            model_name="applications",
            name="national_id",
            field=models.ImageField(null=True, upload_to="final/applicant/ids"),
        ),
        migrations.AlterField(
            model_name="applications",
            name="registration_form",
            field=models.FileField(
                help_text="Insert your Registration/Enrollment Form for the current semester.",
                null=True,
                upload_to="final/applicant/registration_form",
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="voter_certificate",
            field=models.FileField(
                null=True, upload_to="final/applicant/voters_certificate"
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="tempapplications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="tempapplications",
            name="guardians_voter_certificate",
            field=models.FileField(
                help_text="Insert your SCANNED COPY (IMG) guardian's voter certificate (for verification and validation purposes).",
                null=True,
                upload_to="tmp/guardian/voters_certificate",
            ),
        ),
        migrations.AlterField(
            model_name="tempapplications",
            name="informative_copy_of_grades",
            field=models.FileField(null=True, upload_to="tmp/applicant/icg"),
        ),
        migrations.AlterField(
            model_name="tempapplications",
            name="national_id",
            field=models.ImageField(null=True, upload_to="tmp/applicant/ids"),
        ),
        migrations.AlterField(
            model_name="tempapplications",
            name="registration_form",
            field=models.FileField(
                help_text="Insert your Registration/Enrollment Form for the current semester.",
                null=True,
                upload_to="tmp/applicant/registration_form",
            ),
        ),
        migrations.AlterField(
            model_name="tempapplications",
            name="voter_certificate",
            field=models.FileField(
                null=True, upload_to="tmp/applicant/voters_certificate"
            ),
        ),
    ]
