# Generated by Django 4.2.5 on 2024-01-05 14:05

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0068_alter_applications_application_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="elementary_school",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="house_address",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="jhs_school",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="personalized_facebook_link",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="shs_school",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="tempapplications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
    ]
