# Generated by Django 4.2.5 on 2024-01-05 14:15

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0070_alter_applications_applying_for_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardian_complete_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardian_contact_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardian_educational_attainment",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardian_occupation",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="guardian_place_of_work",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applications",
            name="shiftee",
            field=models.CharField(
                default="N/A",
                help_text="Title of your previous course (if shiftee).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applications",
            name="transferee",
            field=models.CharField(
                default="N/A",
                help_text="Name of your previous school/university.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eligibilityconfig",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="tempapplications",
            name="applying_for_academic_year",
            field=application.models.AcademicYearField(
                default=application.models.AcademicYearField.calculate_academic_year,
                editable=False,
                max_length=9,
            ),
        ),
    ]
