# Generated by Django 4.2.5 on 2023-10-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ScholarshipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scholarship_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("middlename", models.CharField(max_length=30, null=True)),
                ("contactnumber", models.CharField(max_length=13)),
                ("house_address", models.CharField(max_length=50)),
                ("barangay", models.CharField(max_length=30)),
                ("district", models.PositiveSmallIntegerField(null=True)),
                ("religion", models.CharField(max_length=30)),
                ("facebookLink", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("yearsOfResidency", models.PositiveSmallIntegerField()),
                ("birthdate", models.DateField()),
                (
                    "gender",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demographics.gender",
                    ),
                ),
            ],
        ),
    ]
