# Generated by Django 4.2.5 on 2023-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0004_alter_applicant_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="facebookLink",
            field=models.CharField(max_length=100),
        ),
    ]
