# Generated by Django 4.2.5 on 2023-10-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0005_alter_applicant_facebooklink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="facebookLink",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
