# Generated by Django 4.2.5 on 2023-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0006_alter_applicant_facebooklink"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
