# Generated by Django 4.2.5 on 2023-10-09 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demographics", "0007_applicant_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="age",
        ),
    ]
