# Generated by Django 4.2.5 on 2023-11-17 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_alter_scholarprofile_scholarship_type"),
        ("demographics", "0013_delete_applicant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScholarshipType",
        ),
    ]
