# Generated by Django 4.2.5 on 2023-11-18 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 18, 14, 32, 31, 961533, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
