# Generated by Django 4.2.5 on 2023-11-18 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 18, 19, 45, 6, 326803, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
