# Generated by Django 4.2.5 on 2023-11-19 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0003_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 3, 12, 42, 692142, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
