# Generated by Django 4.2.5 on 2023-11-19 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0005_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 15, 10, 34, 202101, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
