# Generated by Django 4.2.5 on 2023-11-21 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0011_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 21, 4, 19, 16, 878335, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
