# Generated by Django 4.2.5 on 2023-11-21 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0013_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 21, 14, 9, 48, 962763, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
