# Generated by Django 4.2.5 on 2023-11-22 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0015_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 22, 15, 26, 48, 371607, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
