# Generated by Django 4.2.5 on 2023-11-23 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0016_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 23, 4, 5, 16, 65476, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
