# Generated by Django 4.2.5 on 2023-11-24 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0018_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 24, 14, 43, 59, 974317, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
