# Generated by Django 4.2.5 on 2023-12-01 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0024_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 1, 6, 49, 11, 401934, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
