# Generated by Django 4.2.5 on 2023-12-02 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0026_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 2, 7, 30, 51, 519239, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
