# Generated by Django 4.2.5 on 2023-12-03 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0028_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 15, 52, 19, 423569, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
