# Generated by Django 4.2.5 on 2023-12-05 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0030_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 5, 4, 56, 7, 533003, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
