# Generated by Django 4.2.5 on 2023-12-05 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0031_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 5, 6, 26, 19, 121315, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
