# Generated by Django 4.2.5 on 2023-12-06 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0032_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 6, 9, 49, 41, 951169, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
