# Generated by Django 4.2.5 on 2024-01-13 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0038_alter_passwordreset_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 13, 3, 34, 1, 954529, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
